sudo: required
services: 
  - docker

before_install:
  - docker build -t AnapiDappa/reacttest -f ./client/Dockerfile.dev .
  
script: 
  - docker run -e CI=true AnapiDappa/reacttest npm run test

after_success:
  - docker build -t AnapiDappa/multi-react ./client .
  - docker build -t AnapiDappa/multi-nginx ./nginx .
  - docker build -t AnapiDappa/multi-server ./server .
  - docker build -t AnapiDappa/multi-worker ./worker .  