sudo: required
services: 
  - docker

before_install:
  - docker build -t AnapiDappa/reacttest -f ./client/Dockerfile.dev .
  
script: 
  - docker run -e CI=true AnapiDappa/reacttest npm run test

after_success:
  - docker build -t AnapiDappa/multi-client ./client .
  - docker build -t AnapiDappa/multi-nginx ./nginx .
  - docker build -t AnapiDappa/multi-server ./server .
  - docker build -t AnapiDappa/multi-worker ./worker . 
  # Log in to docker CLI 
  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push them to docker hub
  - docker push AnapiDappa/multi-client
  - docker push AnapiDappa/multi-nginx
  - docker push AnapiDappa/multi-server
  - docker push AnapiDappa/multi-worker

deploy:
  elasticbeanstalk: elasticbeanstalk
  region: eu-north-1
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-eu-north-1-891377167372
  bucket_path: docker-multi
  on:
     branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY