name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t AnapiDappa/reacttest -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true AnapiDappa/reacttest npm test

      - run: docker build -t AnapiDappa/multi-client ./client
      - run: docker build -t AnapiDappa/multi-nginx ./nginx
      - run: docker build -t AnapiDappa/multi-server ./server
      - run: docker build -t AnapiDappa/multi-worker ./worker

      - run: docker push AnapiDappa/multi-client
      - run: docker push AnapiDappa/multi-nginx
      - run: docker push AnapiDappa/multi-server
      - run: docker push AnapiDappa/multi-worker
